### ISSUE TITLE
Update Readme to include instructions to clone submodules

### ISSUE THREAD

**Issue by acere** [aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop#14]
When cloning the repository with 
```terminal
~$ git clone https://github.com/aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop.git
```
the `ml-lineage-helper` folder is not populated.

**Proposed solution**
Update `README.md` to include instructions to clone the repository with the `--recursive` option to include all submodules.
e.g.:
<pre><code>~$ git clone <b>--recursive</b> https://github.com/aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop.git</code>
</pre>

**Comment by pmhargis-aws** [comment]
Updated the README.md file to include instructions for --recursive option.
