### ISSUE TITLE
Sagemaker Client not instantiated in m4_nb3_Inference_pipeline_lookup.ipynb

### ISSUE THREAD

**Issue by stechr** [aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop#15]
Currently m4_nb3_Inference_pipeline_lookup.ipynb is not executable as SageMaker client is not instantiated, but used as : customers_fg = sagemaker_client.describe_feature_group(
    FeatureGroupName=customers_feature_group_name)

To make it work, it needs to be instantiated earlier with 

sagemaker_client = session.client(service_name="sagemaker")

This could be done best in the "Essentials" part of the notebook.

**Comment by pmhargis-aws** [comment]
Fixed via Pull-Request.
