### ISSUE TITLE
Partitions not created

### ISSUE THREAD

**Issue by lindadevenney** [aws-samples/amazon-sagemaker-feature-store-end-to-end-workshop#37]
Using the sample code, when you create the orders feature group (I've slightly modified the name) it does not explicitly create Iceberg partitions.

- Viewed table in Glue and no partitions exist within the Partitions tab under Table Details

- Ran query in Athena and get error
SYNTAX_ERROR: line 1:46: Table awsdatacatalog.sagemaker_featurestore.demo-orders-iceberg-ftrg-1672924461$partitions does not exist

Athena Query: SELECT sum(total_size), sum(file_count) FROM "demo-orders-iceberg-ftrg-1672924461$partitions"

Is this something to do with the way the SageMaker API creates partitioning or do we need to include a partition spec?

https://docs.amazonaws.cn/en_us/sagemaker/latest/dg/feature-store-offline.html
Records in the offline store are partitioned by event time into daily partitions. You can’t configure the partitioning scheme. The following shows an example of the output location of a Parquet file where the event time feature name is EventTime:

s3://DOC-EXAMPLE-BUCKET/example-prefix/account-id/sagemaker/Amazon Web Services Region/offline-store/feature-group-name-feature-group-creation-time/data/**8-random-alphanumeric-digits**/event-time-feature-name_trunc=event-time-year-event-time-month-event-time-day/timestamp-of-latest-event-time-in-file_16-random-alphanumeric-digits.parquet

We would also like to see partitioning follow the same standard as non-ICEBERG tables
s3://DOC-EXAMPLE-BUCKET/example-prefix-name/111122223333/sagemaker/Amazon Web Services Region/offline-store/example-feature-group-account-id/data/year=year/month=month/day=day/hour=hour/timestamp_of_latest_event_time_in_file_16-random-alphanumeric-digits.parquet

**Comment by markproy** [comment]
As documented in the `m2_nb3_offline_iceberg_compaction.ipynb` notebook, that query requires your Athena workgroup to use Athena engine v3 or greater. I'm guessing yours is still at v2, which does not support that specific syntax. Also, regarding your additional request, Iceberg table format is designed differently from the default glue/hive format. Thus, you will not see separate folders for year/month/day/hour.

**Comment by pmhargis-aws** [comment]
Merged Pull-Request to fix problem with iceberg compaction.
